/**
 * Self-contained i18n for the accessibility (IS 5568) UI chrome.
 *
 * Kept separate from the main `t()` dictionary on purpose: the main
 * dictionaries are each typed `Record<TKey, string>`, so adding keys there
 * would force a translation into all 14 languages at compile time. Here we
 * use an English base with per-language overrides that fall back gracefully,
 * mirroring the project convention (UI chrome localized; English is the
 * canonical fallback).
 *
 * These are short, standard accessibility-widget labels — translated for all
 * 14 supported UI languages. The long-form legal accessibility *statement*
 * lives in AccessibilityStatement.tsx as bilingual he/en content, the same
 * way clinical reference copy is handled elsewhere in the app.
 */
import type { Lang } from '../i18n/languages';

export interface A11yLabels {
  /** Short noun — button title / panel heading. */
  title: string;
  menuTitle: string;
  open: string;
  close: string;
  skip: string;
  adjustments: string;
  textSize: string;
  increase: string;
  decrease: string;
  contrast: string;
  grayscale: string;
  links: string;
  headings: string;
  readable: string;
  bigCursor: string;
  stopMotion: string;
  reset: string;
  statement: string;
  on: string;
  off: string;
}

/** English — the canonical base every language falls back to. */
const en: A11yLabels = {
  title: 'Accessibility',
  menuTitle: 'Accessibility menu',
  open: 'Open accessibility menu',
  close: 'Close',
  skip: 'Skip to main content',
  adjustments: 'Display adjustments',
  textSize: 'Text size',
  increase: 'Increase text size',
  decrease: 'Decrease text size',
  contrast: 'High contrast',
  grayscale: 'Monochrome',
  links: 'Highlight links',
  headings: 'Highlight titles',
  readable: 'Readable font',
  bigCursor: 'Large cursor',
  stopMotion: 'Stop animations',
  reset: 'Reset settings',
  statement: 'Accessibility statement',
  on: 'On',
  off: 'Off',
};

const OVERRIDES: Partial<Record<Lang, A11yLabels>> = {
  he: {
    title: 'נגישות',
    menuTitle: 'תפריט נגישות',
    open: 'פתיחת תפריט נגישות',
    close: 'סגירה',
    skip: 'דילוג לתוכן המרכזי',
    adjustments: 'התאמות תצוגה',
    textSize: 'גודל טקסט',
    increase: 'הגדלת טקסט',
    decrease: 'הקטנת טקסט',
    contrast: 'ניגודיות גבוהה',
    grayscale: 'גווני אפור',
    links: 'הדגשת קישורים',
    headings: 'הדגשת כותרות',
    readable: 'גופן קריא',
    bigCursor: 'סמן מוגדל',
    stopMotion: 'עצירת אנימציות',
    reset: 'איפוס הגדרות',
    statement: 'הצהרת נגישות',
    on: 'פעיל',
    off: 'כבוי',
  },
  ar: {
    title: 'إمكانية الوصول',
    menuTitle: 'قائمة إمكانية الوصول',
    open: 'فتح قائمة إمكانية الوصول',
    close: 'إغلاق',
    skip: 'تخطٍّ إلى المحتوى الرئيسي',
    adjustments: 'تعديلات العرض',
    textSize: 'حجم النص',
    increase: 'تكبير النص',
    decrease: 'تصغير النص',
    contrast: 'تباين عالٍ',
    grayscale: 'تدرّج رمادي',
    links: 'إبراز الروابط',
    headings: 'إبراز العناوين',
    readable: 'خط سهل القراءة',
    bigCursor: 'مؤشر كبير',
    stopMotion: 'إيقاف الحركة',
    reset: 'إعادة الضبط',
    statement: 'بيان إمكانية الوصول',
    on: 'مُفعّل',
    off: 'مُعطّل',
  },
  es: {
    title: 'Accesibilidad',
    menuTitle: 'Menú de accesibilidad',
    open: 'Abrir menú de accesibilidad',
    close: 'Cerrar',
    skip: 'Saltar al contenido principal',
    adjustments: 'Ajustes de visualización',
    textSize: 'Tamaño del texto',
    increase: 'Aumentar el texto',
    decrease: 'Reducir el texto',
    contrast: 'Alto contraste',
    grayscale: 'Escala de grises',
    links: 'Resaltar enlaces',
    headings: 'Resaltar títulos',
    readable: 'Fuente legible',
    bigCursor: 'Cursor grande',
    stopMotion: 'Detener animaciones',
    reset: 'Restablecer',
    statement: 'Declaración de accesibilidad',
    on: 'Activado',
    off: 'Desactivado',
  },
  fr: {
    title: 'Accessibilité',
    menuTitle: 'Menu d’accessibilité',
    open: 'Ouvrir le menu d’accessibilité',
    close: 'Fermer',
    skip: 'Aller au contenu principal',
    adjustments: 'Réglages d’affichage',
    textSize: 'Taille du texte',
    increase: 'Agrandir le texte',
    decrease: 'Réduire le texte',
    contrast: 'Contraste élevé',
    grayscale: 'Niveaux de gris',
    links: 'Surligner les liens',
    headings: 'Surligner les titres',
    readable: 'Police lisible',
    bigCursor: 'Grand curseur',
    stopMotion: 'Arrêter les animations',
    reset: 'Réinitialiser',
    statement: 'Déclaration d’accessibilité',
    on: 'Activé',
    off: 'Désactivé',
  },
  de: {
    title: 'Barrierefreiheit',
    menuTitle: 'Barrierefreiheits-Menü',
    open: 'Barrierefreiheits-Menü öffnen',
    close: 'Schließen',
    skip: 'Zum Hauptinhalt springen',
    adjustments: 'Anzeigeeinstellungen',
    textSize: 'Textgröße',
    increase: 'Text vergrößern',
    decrease: 'Text verkleinern',
    contrast: 'Hoher Kontrast',
    grayscale: 'Graustufen',
    links: 'Links hervorheben',
    headings: 'Überschriften hervorheben',
    readable: 'Gut lesbare Schrift',
    bigCursor: 'Großer Mauszeiger',
    stopMotion: 'Animationen stoppen',
    reset: 'Zurücksetzen',
    statement: 'Erklärung zur Barrierefreiheit',
    on: 'Ein',
    off: 'Aus',
  },
  ru: {
    title: 'Доступность',
    menuTitle: 'Меню доступности',
    open: 'Открыть меню доступности',
    close: 'Закрыть',
    skip: 'Перейти к основному содержимому',
    adjustments: 'Настройки отображения',
    textSize: 'Размер текста',
    increase: 'Увеличить текст',
    decrease: 'Уменьшить текст',
    contrast: 'Высокий контраст',
    grayscale: 'Оттенки серого',
    links: 'Выделить ссылки',
    headings: 'Выделить заголовки',
    readable: 'Удобный шрифт',
    bigCursor: 'Крупный курсор',
    stopMotion: 'Остановить анимацию',
    reset: 'Сбросить',
    statement: 'Заявление о доступности',
    on: 'Вкл.',
    off: 'Выкл.',
  },
  pt: {
    title: 'Acessibilidade',
    menuTitle: 'Menu de acessibilidade',
    open: 'Abrir menu de acessibilidade',
    close: 'Fechar',
    skip: 'Ir para o conteúdo principal',
    adjustments: 'Ajustes de exibição',
    textSize: 'Tamanho do texto',
    increase: 'Aumentar o texto',
    decrease: 'Diminuir o texto',
    contrast: 'Alto contraste',
    grayscale: 'Tons de cinza',
    links: 'Destacar links',
    headings: 'Destacar títulos',
    readable: 'Fonte legível',
    bigCursor: 'Cursor grande',
    stopMotion: 'Parar animações',
    reset: 'Redefinir',
    statement: 'Declaração de acessibilidade',
    on: 'Ativado',
    off: 'Desativado',
  },
  it: {
    title: 'Accessibilità',
    menuTitle: 'Menu di accessibilità',
    open: 'Apri il menu di accessibilità',
    close: 'Chiudi',
    skip: 'Vai al contenuto principale',
    adjustments: 'Regolazioni di visualizzazione',
    textSize: 'Dimensione del testo',
    increase: 'Aumenta il testo',
    decrease: 'Riduci il testo',
    contrast: 'Contrasto elevato',
    grayscale: 'Scala di grigi',
    links: 'Evidenzia i link',
    headings: 'Evidenzia i titoli',
    readable: 'Carattere leggibile',
    bigCursor: 'Cursore grande',
    stopMotion: 'Ferma le animazioni',
    reset: 'Reimposta',
    statement: 'Dichiarazione di accessibilità',
    on: 'Attivo',
    off: 'Disattivato',
  },
  zh: {
    title: '无障碍',
    menuTitle: '无障碍菜单',
    open: '打开无障碍菜单',
    close: '关闭',
    skip: '跳转到主要内容',
    adjustments: '显示调整',
    textSize: '文字大小',
    increase: '增大文字',
    decrease: '减小文字',
    contrast: '高对比度',
    grayscale: '灰度',
    links: '突出显示链接',
    headings: '突出显示标题',
    readable: '易读字体',
    bigCursor: '大号光标',
    stopMotion: '停止动画',
    reset: '重置',
    statement: '无障碍声明',
    on: '开',
    off: '关',
  },
  hi: {
    title: 'सुलभता',
    menuTitle: 'सुलभता मेन्यू',
    open: 'सुलभता मेन्यू खोलें',
    close: 'बंद करें',
    skip: 'मुख्य सामग्री पर जाएँ',
    adjustments: 'प्रदर्शन समायोजन',
    textSize: 'पाठ का आकार',
    increase: 'पाठ बड़ा करें',
    decrease: 'पाठ छोटा करें',
    contrast: 'उच्च कंट्रास्ट',
    grayscale: 'श्वेत-श्याम',
    links: 'लिंक हाइलाइट करें',
    headings: 'शीर्षक हाइलाइट करें',
    readable: 'सुपाठ्य फ़ॉन्ट',
    bigCursor: 'बड़ा कर्सर',
    stopMotion: 'एनिमेशन रोकें',
    reset: 'रीसेट करें',
    statement: 'सुलभता वक्तव्य',
    on: 'चालू',
    off: 'बंद',
  },
  ja: {
    title: 'アクセシビリティ',
    menuTitle: 'アクセシビリティメニュー',
    open: 'アクセシビリティメニューを開く',
    close: '閉じる',
    skip: 'メインコンテンツへスキップ',
    adjustments: '表示の調整',
    textSize: '文字サイズ',
    increase: '文字を大きく',
    decrease: '文字を小さく',
    contrast: 'ハイコントラスト',
    grayscale: 'グレースケール',
    links: 'リンクを強調',
    headings: '見出しを強調',
    readable: '読みやすいフォント',
    bigCursor: '大きいカーソル',
    stopMotion: 'アニメーションを停止',
    reset: 'リセット',
    statement: 'アクセシビリティに関する声明',
    on: 'オン',
    off: 'オフ',
  },
  tr: {
    title: 'Erişilebilirlik',
    menuTitle: 'Erişilebilirlik menüsü',
    open: 'Erişilebilirlik menüsünü aç',
    close: 'Kapat',
    skip: 'Ana içeriğe geç',
    adjustments: 'Görüntü ayarları',
    textSize: 'Metin boyutu',
    increase: 'Metni büyüt',
    decrease: 'Metni küçült',
    contrast: 'Yüksek kontrast',
    grayscale: 'Gri tonlama',
    links: 'Bağlantıları vurgula',
    headings: 'Başlıkları vurgula',
    readable: 'Okunaklı yazı tipi',
    bigCursor: 'Büyük imleç',
    stopMotion: 'Animasyonları durdur',
    reset: 'Sıfırla',
    statement: 'Erişilebilirlik beyanı',
    on: 'Açık',
    off: 'Kapalı',
  },
  pl: {
    title: 'Dostępność',
    menuTitle: 'Menu dostępności',
    open: 'Otwórz menu dostępności',
    close: 'Zamknij',
    skip: 'Przejdź do treści głównej',
    adjustments: 'Ustawienia wyświetlania',
    textSize: 'Rozmiar tekstu',
    increase: 'Powiększ tekst',
    decrease: 'Zmniejsz tekst',
    contrast: 'Wysoki kontrast',
    grayscale: 'Skala szarości',
    links: 'Wyróżnij linki',
    headings: 'Wyróżnij nagłówki',
    readable: 'Czytelna czcionka',
    bigCursor: 'Duży kursor',
    stopMotion: 'Zatrzymaj animacje',
    reset: 'Resetuj',
    statement: 'Deklaracja dostępności',
    on: 'Wł.',
    off: 'Wył.',
  },
};

/** Resolve the accessibility UI labels for a language (English fallback). */
export function a11yStrings(lang: Lang): A11yLabels {
  return OVERRIDES[lang] ?? en;
}
